##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Historic Bloomington Walking Tours
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A collection of historic walking tour brochures produced in Bloomington, Indiana
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: This is a digitized collection of photographs I took of the tour sites from 15 self-guided walking tour brochures produced between 2002 and 2017 by the City of Bloomington Department of Housing and Neighborhood Development. All rights to these brochures belong to the City of Bloomington Department of Housing and Neighborhood Development. The brochures were created to generate interest in prevalent architecture forms and local history in Bloomington, Indiana. pdfs of the original brochures can be found on the "Brochures" tab of this website or on the City of Bloomington's website. Physical copies are disseminated at the Monroe County History Center.
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: chase_hastin

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: bloomington_walking_tours

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: ILS-Z 652 Digital Libraries, Indiana University
# organization-link: https://jawalsh.github.io/z652-Digital-Libraries-FA25/ 
# organization-logo-banner: 
# organization-logo-nav: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
